services:
  # Backend API Service
  - type: web
    name: devbooking-api
    runtime: node
    plan: free # You can upgrade to 'starter' or higher for production
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: devbooking-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-domain.onrender.com # Update this after deployment
      # Add your API keys here
      - key: TWILIO_ACCOUNT_SID
        sync: false # Set in Render dashboard
      - key: TWILIO_AUTH_TOKEN
        sync: false # Set in Render dashboard
      - key: TWILIO_PHONE_NUMBER
        sync: false # Set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false # Set in Render dashboard
      - key: SENDGRID_API_KEY
        sync: false # Set in Render dashboard
      - key: SENDGRID_FROM_EMAIL
        sync: false # Set in Render dashboard
      - key: SENDGRID_FROM_NAME
        sync: false # Set in Render dashboard
      - key: HELCIM_API_TOKEN
        sync: false # Set in Render dashboard
      - key: HELCIM_API_URL
        value: https://api.helcim.com/v2
      - key: HELCIM_WEBHOOK_VERIFIER_TOKEN
        sync: false # Set in Render dashboard
      - key: VITE_HELCIM_ACCOUNT_ID
        sync: false # Set in Render dashboard
      - key: VITE_HELCIM_TERMINAL_ID
        sync: false # Set in Render dashboard
      - key: VITE_HELCIM_JS_TOKEN
        sync: false # Set in Render dashboard
      - key: AWS_ACCESS_KEY_ID
        sync: false # Set in Render dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false # Set in Render dashboard
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false # Set in Render dashboard
      - key: REDIS_URL
        sync: false # Optional - set if using Redis
      - key: BUSINESS_NAME
        value: Your Salon Name
      - key: BUSINESS_PHONE
        value: +1234567890
      - key: BUSINESS_EMAIL
        value: info@yoursalon.com
      - key: ADMIN_EMAIL
        value: admin@yoursalon.com
      - key: ADMIN_PASSWORD
        sync: false # Set in Render dashboard
      - key: DISABLE_AUTOMATIC_SERVICE_CREATION
        value: true

  # Frontend Static Site
  - type: static
    name: devbooking-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://devbooking-api.onrender.com # Update this after API deployment
      - key: VITE_HELCIM_ACCOUNT_ID
        sync: false # Set in Render dashboard
      - key: VITE_HELCIM_JS_TOKEN
        sync: false # Set in Render dashboard
      - key: VITE_HELCIM_TERMINAL_ID
        sync: false # Set in Render dashboard

databases:
  - name: devbooking-db
    plan: free # You can upgrade for production
    databaseName: devbooking_production
    user: devbooking_user
    # PostgreSQL version 15
    version: "15"

# Optional: Redis for caching
# - name: devbooking-redis
#   type: redis
#   plan: free
#   maxmemoryPolicy: allkeys-lfu
